const source = 'https://adilet.zan.kz/rus/docs/K2500000214/file_214.htm';
const topics = [
  {tag:'ФНО 270.00', article:'Статья 418 НК РК', title:'Когда сдавать ФНО 270.00?', summary:'Декларацию о доходах и имуществе за 2025 год нужно представить не позднее 15 сентября 2026 года. При самостоятельной уплате ИПН срок платежа — до 25 сентября.', details:'ФНО 270.00 подают только при наличии предусмотренного законом основания. В частности, её представляет человек, который в 2025 году подал работодателю заявление на предварительный вычет по вознаграждению ипотечного жилищного займа. Подготовьте договор займа, график и банковскую справку об уплаченных процентах. Не заявляйте повторно сумму, которую работодатель уже учёл как вычет.', terms:['фно','270','270.00','декларация','срок','сдавать','вычет','ипотека','заём','займ','банковский','кредит','работодатель','15 сентября']},
  {tag:'НДС', article:'Статья 460', title:'Когда возникает НДС?', summary:'Дата оборота зависит от вида операции. Для товара это обычно момент отгрузки; для работ и услуг действуют отдельные правила.', details:'Начните с определения вида сделки и даты первого подтверждающего события. Затем проверьте специальные случаи в самой статье.', terms:['ндс','возникает','оборот','отгрузка','услуг','товар']},
  {tag:'НДС', article:'Статья 457', title:'Кто должен платить НДС?', summary:'Плательщиками НДС признаются лица, состоящие на регистрационном учёте по НДС, а также лица в случаях, предусмотренных кодексом.', details:'Регистрация и обязанность уплачивать налог зависят от статуса лица, оборота и характера операции. Проверьте применимые исключения.', terms:['плательщик','регистрация','вставать','ндс','должен','платить']},
  {tag:'НДС', article:'Статья 459', title:'Где считается реализованной услуга?', summary:'Место реализации влияет на то, облагается ли операция в Казахстане. Для разных услуг Кодекс устанавливает разные критерии.', details:'Для услуг важны их вид, местонахождение имущества и статус заказчика. Это особенно существенно при работе с нерезидентом.', terms:['место','реализации','нерезидент','услуга','зарубеж','иностран']},
  {tag:'ОБОРОТ', article:'Статья 461', title:'Как определить размер оборота?', summary:'Размер оборота обычно определяется исходя из стоимости реализованных товаров, работ или услуг без включения НДС.', details:'В отдельных ситуациях действуют правила корректировки и особые способы определения суммы. Откройте норму для деталей.', terms:['размер','оборот','стоимость','сумма','выручка','доход']}
];
const cards = document.querySelector('#cards'); const template = document.querySelector('#cardTemplate');
function render(items, searched=false){ cards.innerHTML=''; document.querySelector('.count').textContent = searched ? `Найдено: ${items.length}` : '5 материалов в базе';
 if(!items.length){cards.innerHTML='<div class="empty"><strong>Точного совпадения пока нет.</strong><br>Попробуйте сформулировать вопрос короче или используйте слова «НДС», «оборот», «услуги».</div>';return}
 items.forEach(item=>{const n=template.content.cloneNode(true);n.querySelector('.tag').textContent=item.tag;n.querySelector('.article').textContent=item.article;n.querySelector('h3').textContent=item.title;n.querySelector('.summary').textContent=item.summary;n.querySelector('.details').textContent=item.details;const a=n.querySelector('.source');a.href=source;n.querySelector('.detail').addEventListener('click',e=>{const card=e.currentTarget.closest('.card');card.classList.toggle('open');e.currentTarget.firstChild.textContent=card.classList.contains('open')?'Свернуть ':'Подробнее '});cards.append(n)});}
function search(value){const q=value.toLowerCase().trim();const words=q.split(/\s+/).filter(w=>w.length>2);const found=topics.filter(t=>words.some(w=>[t.title,t.summary,t.details,...t.terms].join(' ').toLowerCase().includes(w)));render(found,true);document.querySelector('.section-heading h2').textContent=q?`Ответы на: «${value}»`:'Популярные темы'}
document.querySelector('#searchForm').addEventListener('submit',e=>{e.preventDefault();search(document.querySelector('#query').value)});document.querySelectorAll('.examples button').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#query').value=b.textContent;search(b.textContent);document.querySelector('#results').scrollIntoView({behavior:'smooth'})}));render(topics);
